---
- name: Verify
  hosts: all
  become: yes
  gather_facts: yes

  tasks:
    # Test we can logon to 'webservers' and execute python with json lib.
    # ansible webservers -m ping

    - name: Test connection is available
      ansible.builtin.ping:
